import { useState, type FormEvent } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Check, CircleHelp, FilePlus2, Fingerprint, LockKeyhole, Plus, ShieldCheck, Trash2, UploadCloud } from 'lucide-react';
import { getGetAtlasOverviewQueryKey, getGetAtlasSessionQueryKey, getGetAtlasSourcesQueryKey, getGetAtlasSourceQueryKey, getGetMyTwinQueryKey, getGetStorageObjectQueryKey, useAnalyzeAtlasSource, useCreateAtlasSource, useCreateAtlasWorkspace, useDeleteAtlasSource, useGetAtlasOverview, useGetAtlasSource, useGetAtlasSources, useGetMyTwin, useGetStorageObject, useRequestUploadUrl, useUpdateMyTwinAutonomy, useUpdateMyTwinField, type AtlasSource, type ProfileSuggestion, type TwinFieldKey, type SourceKind } from '@workspace/api-client-react';
import { Empty, ErrorState, GoverningNote, Load, Modal, PageHead, displayKey, formatDate, navCards } from '@/components/atlas-ui';

function useRefresh(keys: readonly (readonly string[])[]) { const qc=useQueryClient(); return ()=>keys.forEach(key=>qc.invalidateQueries({queryKey:key})); }
export function Onboarding() {
  const [name,setName]=useState(''); const [industry,setIndustry]=useState(''); const [error,setError]=useState('');
  const create=useCreateAtlasWorkspace(); const refresh=useRefresh([getGetAtlasSessionQueryKey(),getGetAtlasOverviewQueryKey()]);
  const submit=(e:FormEvent)=>{e.preventDefault();setError('');create.mutate({data:{name:name.trim(),industry:industry.trim()}},{onSuccess:refresh,onError:()=>setError('Could not create your workspace. Please try again.')});};
  return <div className="auth-layout" style={{minHeight:'100dvh'}}>
    <div style={{background:'#292538',color:'#f5f0e8',padding:'clamp(30px,6vw,95px)',display:'flex',flexDirection:'column',justifyContent:'space-between',minHeight:450}}>
      <div style={{fontSize:23,fontWeight:700,letterSpacing:'-.06em'}}>atlas<span style={{color:'#e5a483'}}>.</span></div>
      <div><div className="eyebrow" style={{color:'#dfa987'}}>01 / BEGIN WITH A BOUNDARY</div><h1 style={{fontSize:'clamp(46px,5vw,82px)',letterSpacing:'-.07em',lineHeight:'.98',margin:'20px 0'}}>A twin that starts<br/><span className="serif" style={{color:'#dce9aa'}}>with you.</span></h1><p style={{color:'#aaa4b4',maxWidth:430,lineHeight:1.65,fontSize:14}}>Nothing is imported, inferred, or analyzed by default. Set up a private space, then decide what belongs inside it.</p></div>
      <div style={{fontSize:11,color:'#aaa4b4'}}>Your evidence. Your boundaries. Your final say.</div>
    </div>
    <div style={{display:'grid',placeItems:'center',padding:30}}><form onSubmit={submit} style={{width:'min(100%,440px)'}}>
      <div className="eyebrow">WORKSPACE SETUP</div><h2 className="page-title" style={{fontSize:40}}>Make room for <em>your work.</em></h2><p className="page-lede" style={{marginBottom:32}}>Give your space a name. No other information is required to begin.</p>
      <div className="field"><label className="label" htmlFor="workspace-name">Workspace name</label><input id="workspace-name" className="input" value={name} onChange={e=>setName(e.target.value)} maxLength={120} required placeholder="Name this workspace" data-testid="input-workspace-name"/></div>
      <div className="field"><label className="label" htmlFor="workspace-industry">Industry</label><input id="workspace-industry" className="input" value={industry} onChange={e=>setIndustry(e.target.value)} maxLength={100} required placeholder="Your industry" data-testid="input-workspace-industry"/></div>
      <GoverningNote>Atlas starts empty. Enterprise connections and live meeting attendance are not available in this release.</GoverningNote>
      {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
      <button className="btn btn-primary" style={{width:'100%',marginTop:25}} disabled={create.isPending} data-testid="button-create-workspace">{create.isPending?'Creating workspace…':'Create workspace'} <ArrowRight size={15}/></button>
    </form></div>
  </div>;
}

export function Overview() {
  const q=useGetAtlasOverview();
  if(q.isLoading)return <Load count={4}/>; if(q.isError)return <ErrorState retry={()=>q.refetch()}/>;
  const o=q.data; if(!o)return null;
  const counts=[['Your twins',o.counts.twins],['Sources',o.counts.sources],['Meetings',o.counts.meetings],['Pending reviews',o.counts.pendingDecisions],['Open actions',o.counts.actions],['Knowledge links',o.counts.knowledgeLinks]];
  return <>
    <PageHead eyebrow="WORKSPACE / OVERVIEW" title="A clearer picture," italic="on your terms." description={`Welcome to ${o.workspace.name}. This is a space for evidence you choose to bring in, and decisions you choose to make.`}/>
    <div className="grid-two">
      <div className="card" style={{background:'#302b3f',color:'#f8f2e7',padding:'clamp(25px,4vw,44px)',minHeight:280,position:'relative',overflow:'hidden'}}>
        <div style={{position:'absolute',right:-35,top:-90,width:310,height:310,border:'1px solid #625a71',borderRadius:'50%',boxShadow:'0 0 0 37px #302b3f,0 0 0 38px #625a71,0 0 0 78px #302b3f,0 0 0 79px #625a71',opacity:.65}}/>
        <div className="eyebrow" style={{color:'#d9ad8d'}}>YOUR ATLAS / CURRENT STATE</div>
        <h2 style={{fontSize:'clamp(27px,3vw,40px)',lineHeight:1.1,letterSpacing:'-.045em',maxWidth:430,margin:'31px 0 13px',position:'relative'}}>Built on what you know.<br/><span className="serif" style={{color:'#dce9aa'}}>Not what we assume.</span></h2>
        <p style={{color:'#bdb5c8',fontSize:12,lineHeight:1.6,maxWidth:340,position:'relative'}}>Start by reviewing your twin’s profile, or add a source you have permission to use.</p>
        <Link href="/twin" className="btn" style={{background:'#e2e9b9',color:'#292538',marginTop:14,position:'relative'}} data-testid="link-start-twin">Review my twin <ArrowUpRight size={15}/></Link>
      </div>
      <div className="card card-pad" style={{minHeight:280}}>
        <div className="eyebrow">PROFILE CALIBRATION</div>
        <div style={{display:'flex',alignItems:'baseline',gap:9,margin:'22px 0 16px'}}><span style={{fontSize:53,letterSpacing:'-.08em',lineHeight:1}} data-testid="text-profile-completion">{o.profileCompletion}%</span><span className="muted tiny">reviewed</span></div>
        <div style={{height:6,background:'#e8e2da',borderRadius:5,overflow:'hidden'}}><div style={{height:'100%',width:`${o.profileCompletion}%`,background:'#c65131',transition:'width .4s'}}/></div>
        <p className="muted" style={{fontSize:12,lineHeight:1.6,marginTop:22}}>{o.profileCompletion===0?'No fields have been confirmed yet. Unknown is an honest starting point.':'Profile completion reflects fields you have personally reviewed.'}</p>
      </div>
    </div>
    <div className="section-heading"><h2>Workspace at a glance</h2><span>LIVE COUNTS</span></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{counts.map(([label,value])=><div className="card" style={{padding:'18px 20px'}} key={label}><div style={{fontSize:29,letterSpacing:'-.06em',fontWeight:600}} data-testid={`count-${String(label).toLowerCase().replaceAll(' ','-')}`}>{value}</div><div className="muted tiny" style={{marginTop:8}}>{label}</div></div>)}</div>
    {o.setupNeeds.length>0&&<><div className="section-heading"><h2>Still to set up</h2><span>YOUR PACE</span></div><div className="notice"><CircleHelp/>{o.setupNeeds.join(' · ')}</div></>}
    <div className="section-heading"><h2>Find your starting point</h2><span>EXPLORE</span></div>
    <div className="grid-two" style={{gridTemplateColumns:'repeat(2,minmax(0,1fr))'}}>{navCards.map(({href,title,copy,icon:Icon})=><Link href={href} className="card card-pad" style={{display:'block',transition:'transform .2s'}} key={href} data-testid={`link-setup-${href.slice(1)}`}><Icon size={20} color="#c65131" strokeWidth={1.6}/><h3 style={{fontSize:16,margin:'20px 0 7px'}}>{title} <ArrowUpRight size={14} style={{float:'right'}}/></h3><p className="muted tiny" style={{lineHeight:1.6,margin:0}}>{copy}</p></Link>)}</div>
  </>;
}

export function Twin() {
  const q=useGetMyTwin(); const field=useUpdateMyTwinField(); const autonomy=useUpdateMyTwinAutonomy(); const refresh=useRefresh([getGetMyTwinQueryKey(),getGetAtlasOverviewQueryKey()]);
  const [editing,setEditing]=useState<TwinFieldKey|null>(null); const [value,setValue]=useState(''); const [sourceIds,setSourceIds]=useState(''); const [level,setLevel]=useState<number|null>(null); const [reason,setReason]=useState(''); const [error,setError]=useState('');
  const keys: TwinFieldKey[]=['role','expertise','priorities','communicationStyle','decisionMethodology','riskTolerance','delegationRules','approvalLimits','meetingBehavior','stakeholderRelationships'];
  if(q.isLoading)return <Load count={4}/>; if(q.isError)return <ErrorState retry={()=>q.refetch()}/>;
  const t=q.data; if(!t)return null;
  const currentLevel=level??t.autonomy.level;
  return <><PageHead eyebrow="IDENTITY / CALIBRATION" title="Your twin," italic="your truth." description="A working profile, not a guess. Every field stays unknown until you review it. Correct anything, any time." action={<div className="badge green"><ShieldCheck size={12}/> Personally reviewed</div>}/>
    <div className="grid-two">
      <div><div className="card card-pad" style={{display:'flex',alignItems:'center',gap:22,marginBottom:20}}><div style={{width:65,height:65,borderRadius:'50%',background:'#e1e7bd',display:'grid',placeItems:'center',color:'#3c3a40',flex:'none'}}><Fingerprint size={29} strokeWidth={1.3}/></div><div><div className="eyebrow">TWIN PROFILE</div><h2 style={{margin:'8px 0 3px',fontSize:22,letterSpacing:'-.04em'}}>{t.displayName || 'Your profile'}</h2><span className="muted tiny">{t.profileCompletion}% reviewed · {t.fields.filter(f=>f.evidenceStatus==='confirmed').length} confirmed fields</span></div></div>
        <div className="section-heading" style={{marginTop:0}}><h2>Profile fields</h2><span>REVIEW INDIVIDUALLY</span></div>
        <div className="card card-pad">{keys.map(key=>{const f=t.fields.find(x=>x.key===key);return <div className="row" key={key}><div style={{minWidth:0,flex:1}}><div style={{display:'flex',alignItems:'center',gap:9,marginBottom:5}}><h3 className="row-title" style={{margin:0}}>{displayKey(key)}</h3><span className={`badge ${f?.evidenceStatus==='confirmed'?'green':f?.evidenceStatus==='inferred'?'orange':''}`}>{f?.evidenceStatus||'unknown'}</span></div><p className="row-sub" style={{whiteSpace:'pre-wrap'}} data-testid={`text-field-${key}`}>{f?.value || 'Not provided yet'}</p>{f?.sourceIds&&f.sourceIds.length>0&&<p className="row-sub">{f.sourceIds.length} linked source{f.sourceIds.length!==1?'s':''}</p>}</div><button className="btn btn-outline" onClick={()=>{setEditing(key);setValue(f?.value||'');setSourceIds(f?.sourceIds.join(', ')||'');setError('');}} data-testid={`button-edit-${key}`}>{f?.value?'Review':'Add'}</button></div>})}</div>
      </div>
      <div className="stack"><div className="card card-pad"><div className="eyebrow">AUTONOMY CEILING</div><h2 style={{fontSize:23,letterSpacing:'-.04em',margin:'16px 0 7px'}}>Boundaries first.</h2><p className="muted tiny" style={{lineHeight:1.6}}>Set a ceiling for assistance. This does not authorize Atlas to take consequential decisions on your behalf.</p>
        <div style={{display:'flex',alignItems:'baseline',gap:8,margin:'22px 0 12px'}}><strong style={{fontSize:38,letterSpacing:'-.07em'}}>{currentLevel}</strong><span className="muted tiny mono">/ 10</span></div>
        <input type="range" min={1} max={10} value={currentLevel} onChange={e=>setLevel(Number(e.target.value))} style={{width:'100%',accentColor:'#c65131'}} data-testid="input-autonomy-level"/><div className="row-sub" style={{marginTop:8}}>{t.autonomy.label} · {t.autonomy.approvalRequired?'Approval required':'Review policy applies'}</div>
        {level!==null&&level!==t.autonomy.level&&<><label className="label" style={{marginTop:20}} htmlFor="autonomy-reason">Why change this boundary?</label><textarea id="autonomy-reason" className="input" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} required placeholder="Document your reason" data-testid="input-autonomy-reason"/><button className="btn btn-primary" style={{marginTop:12}} disabled={!reason.trim()||autonomy.isPending} onClick={()=>autonomy.mutate({data:{level:currentLevel,reason:reason.trim()}},{onSuccess:()=>{setLevel(null);setReason('');refresh();},onError:()=>setError('Could not update autonomy.')})} data-testid="button-save-autonomy">Save boundary</button></>}
      </div><GoverningNote>All consequential decisions require human review, regardless of autonomy level. No enterprise system is connected in this release.</GoverningNote></div>
    </div>
    {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
    {editing&&<Modal title={`Review ${displayKey(editing)}`} subtitle="Your entry becomes a personally confirmed profile field." onClose={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();field.mutate({data:{key:editing,value:value.trim(),sourceIds:sourceIds.split(',').map(x=>x.trim()).filter(Boolean)}},{onSuccess:()=>{setEditing(null);refresh();},onError:()=>setError('Could not save this field.')});}}><div className="field"><label className="label" htmlFor="field-value">What should your twin know?</label><textarea className="input" id="field-value" value={value} onChange={e=>setValue(e.target.value)} maxLength={6000} style={{minHeight:170}} placeholder="Leave blank if this remains unknown" data-testid="input-field-value"/></div><div className="field"><label className="label" htmlFor="field-sources">Source IDs (optional, comma-separated)</label><input className="input" id="field-sources" value={sourceIds} onChange={e=>setSourceIds(e.target.value)} placeholder="Link only sources you have reviewed" data-testid="input-field-sources"/></div><div className="dialog-actions"><button type="button" className="btn btn-outline" onClick={()=>setEditing(null)}>Cancel</button><button className="btn btn-primary" disabled={field.isPending} data-testid="button-save-field">Save review</button></div></form></Modal>}
  </>;
}

function SourceDetail({sourceId,onClose,onDeleted}:{sourceId:string;onClose:()=>void;onDeleted:()=>void}) {
  const q=useGetAtlasSource(sourceId,{query:{queryKey:getGetAtlasSourceQueryKey(sourceId),enabled:!!sourceId}});
  const analyze=useAnalyzeAtlasSource(); const remove=useDeleteAtlasSource(); const update=useUpdateMyTwinField(); const refresh=useRefresh([getGetAtlasSourcesQueryKey(),getGetMyTwinQueryKey(),getGetAtlasOverviewQueryKey()]);
  const [analysis,setAnalysis]=useState<ProfileSuggestion[]|null>(null); const [confirm,setConfirm]=useState(false); const [error,setError]=useState('');
  const s=q.data;
  const suggestions=analysis??(s?.analysisStatus==='suggestions_ready'?s.analysisSuggestions:null);
  const readableFormat=!s?.contentType||s.contentType==='text/plain'||s.contentType==='text/markdown';
  return <Modal title={s?.title||'Source details'} subtitle="Nothing becomes part of your profile without your review." onClose={onClose}>{q.isLoading?<Load count={1}/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:s&&<>
    <div style={{display:'flex',gap:8,marginBottom:17}}><span className="badge">{s.kind}</span><span className={`badge ${s.profileAnalysisConsent?'green':'orange'}`}>{s.profileAnalysisConsent?'Analysis consent given':'Analysis not permitted'}</span></div>
    <div className="row"><div><div className="row-title">Added</div><div className="row-sub">{formatDate(s.createdAt)}</div></div><div><div className="row-title">Analysis</div><div className="row-sub">{displayKey(s.analysisStatus)}</div></div></div>
    {!readableFormat?<GoverningNote>This file is stored privately, but profile analysis currently supports notes, text, and Markdown only. PDF and Word extraction is not available yet.</GoverningNote>:s.profileAnalysisConsent&&s.permissionConfirmed?<div style={{marginTop:22}}><label className="checkbox-row"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)} data-testid="checkbox-confirm-analysis"/><span>I confirm I have permission to use this source and explicitly request profile suggestions from it now.</span></label><button className="btn btn-primary" disabled={!confirm||analyze.isPending} style={{marginTop:14}} onClick={()=>analyze.mutate({sourceId:s.id,data:{confirmAnalysis:true}},{onSuccess:res=>{setAnalysis(res.suggestions);refresh();},onError:()=>setError('Analysis could not be completed.')})} data-testid="button-analyze-source">{analyze.isPending?'Analyzing…':'Request analysis'} <ArrowUpRight/></button></div>:<GoverningNote>This source was not authorized for profile analysis. Delete it and add a new source if your permission changes.</GoverningNote>}
    {suggestions&&<div style={{marginTop:25}}><div className="section-heading"><h2>Review suggestions</h2><span>NOT APPLIED AUTOMATICALLY</span></div>{suggestions.length===0?<Empty title="No suggestions found" description="Nothing was added to your profile. The source remains available as evidence."/>:suggestions.map((suggestion,i)=><div className="card card-pad" style={{marginBottom:10}} key={i}><div className="eyebrow">{displayKey(suggestion.key)} · {Math.round(suggestion.confidence*100)}% confidence</div><p style={{fontSize:13,lineHeight:1.6,whiteSpace:'pre-wrap'}}>{suggestion.suggestedValue}</p><p className="row-sub">Evidence: {suggestion.evidence}</p><button className="btn btn-outline" disabled={update.isPending} onClick={()=>update.mutate({data:{key:suggestion.key,value:suggestion.suggestedValue,sourceIds:[s.id]}},{onSuccess:refresh,onError:()=>setError('Could not confirm suggestion.')})} data-testid={`button-confirm-suggestion-${i}`}><Check/> Confirm to profile</button></div>)}</div>}
    {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
    <div className="dialog-actions" style={{justifyContent:'space-between',borderTop:'1px solid #ded9d2',paddingTop:16}}><button className="btn btn-danger" disabled={remove.isPending} onClick={()=>{if(window.confirm('Delete this source? This also removes its eligibility for analysis.'))remove.mutate({sourceId:s.id},{onSuccess:()=>{refresh();onDeleted();},onError:()=>setError('Could not delete source.')});}} data-testid="button-delete-source"><Trash2/> Delete source</button><button className="btn btn-outline" onClick={onClose}>Close</button></div>
  </>}</Modal>;
}

export function Sources() {
  const q=useGetAtlasSources(); const create=useCreateAtlasSource(); const upload=useRequestUploadUrl(); const refresh=useRefresh([getGetAtlasSourcesQueryKey(),getGetAtlasOverviewQueryKey()]);
  const [open,setOpen]=useState(false);const [selected,setSelected]=useState<string|null>(null); const [kind,setKind]=useState<SourceKind>('note'); const [title,setTitle]=useState('');const [content,setContent]=useState('');const [file,setFile]=useState<File|null>(null);const [permission,setPermission]=useState(false);const [consent,setConsent]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false); const [uploadedPath,setUploadedPath]=useState('');
  // Private object reads are available only for known paths from this session; source list intentionally does not expose storage paths.
  const objectQuery=useGetStorageObject(uploadedPath.replace(/^\/objects\//,''),{query:{queryKey:getGetStorageObjectQueryKey(uploadedPath.replace(/^\/objects\//,'')),enabled:false}});
  const save=async(e:FormEvent)=>{e.preventDefault();setError('');if(!permission)return setError('Confirm you have permission before adding a source.');setBusy(true);try{let objectPath: string|undefined; if(file){const signed=await upload.mutateAsync({data:{name:file.name,size:file.size,contentType:file.type||'application/octet-stream'}});const response=await fetch(signed.uploadURL,{method:'PUT',body:file,headers:{'Content-Type':file.type||'application/octet-stream'}});if(!response.ok)throw new Error('The file upload failed.');objectPath=signed.objectPath;setUploadedPath(objectPath);}await create.mutateAsync({data:{title:title.trim(),kind:file?'document':kind,content:file?null:content.trim(),objectPath:objectPath||null,contentType:file?file.type||'application/octet-stream':null,permissionConfirmed:true,profileAnalysisConsent:consent}});refresh();setOpen(false);setTitle('');setContent('');setFile(null);setPermission(false);setConsent(false);}catch(err){setError(err instanceof Error?err.message:'Could not add source.');}finally{setBusy(false);}};
  return <><PageHead eyebrow="EVIDENCE / SOURCES" title="Start with" italic="evidence." description="Add only material you are authorized to use. A source is never analyzed unless you opt in and explicitly confirm a separate analysis request." action={<button className="btn btn-primary" onClick={()=>{setError('');setOpen(true);}} data-testid="button-add-source"><Plus/> Add source</button>}/>
    <GoverningNote>Private files stay attached to your workspace. Adding a source does not analyze it. Enterprise connectors are not available in this release.</GoverningNote>
    <div className="section-heading"><h2>Your sources</h2><span>{q.data?.length??'—'} RECORDS</span></div>
    {q.isLoading?<Load/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:!q.data?.length?<Empty icon={FilePlus2} title="No sources yet" description="Begin with a note or a private document you have permission to use. You decide if analysis is ever allowed." action={<button className="btn btn-dark" onClick={()=>setOpen(true)} data-testid="button-add-first-source"><Plus/> Add first source</button>}/>:<div className="card card-pad">{q.data.map((s:AtlasSource)=><button key={s.id} onClick={()=>setSelected(s.id)} className="row" style={{width:'100%',background:'none',borderLeft:0,borderRight:0,borderTop:0,textAlign:'left',cursor:'pointer'}} data-testid={`button-source-${s.id}`}><div><div className="row-title">{s.title}</div><p className="row-sub">{displayKey(s.kind)} · Added {formatDate(s.createdAt)}</p></div><div style={{display:'flex',alignItems:'center',gap:10}}><span className={`badge ${s.profileAnalysisConsent?'green':'orange'}`}>{s.profileAnalysisConsent?'Consented':'No analysis consent'}</span><ArrowUpRight size={16}/></div></button>)}</div>}
    {selected&&<SourceDetail sourceId={selected} onClose={()=>setSelected(null)} onDeleted={()=>setSelected(null)}/>}
    {open&&<Modal title="Add a source" subtitle="Choose what to share. Analysis is off unless you explicitly opt in." onClose={()=>setOpen(false)}><form onSubmit={save}>
      <div className="field"><label className="label" htmlFor="source-title">Title</label><input className="input" id="source-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={240} required placeholder="A clear name for this source" data-testid="input-source-title"/></div>
      <div className="field"><label className="label" htmlFor="source-kind">Source type</label><select className="input" id="source-kind" value={kind} onChange={e=>setKind(e.target.value as SourceKind)} disabled={!!file} data-testid="select-source-kind">{(['note','email','chat','meeting','decision','document','other'] as SourceKind[]).map(k=><option value={k} key={k}>{displayKey(k)}</option>)}</select></div>
      <div className="field"><label className="label" htmlFor="source-content">Your note (optional if uploading a file)</label><textarea className="input" id="source-content" value={content} onChange={e=>setContent(e.target.value)} disabled={!!file} placeholder="Paste or write the material you want to retain" data-testid="input-source-content"/></div>
      <div className="field"><label className="label" htmlFor="source-file">Or upload a private file</label><input className="input" id="source-file" type="file" accept=".txt,.md,.pdf,.docx" onChange={e=>setFile(e.target.files?.[0]||null)} data-testid="input-source-file"/><p className="row-sub" style={{marginTop:7}}><UploadCloud size={12} style={{display:'inline'}}/> Up to 10 MB. Uploaded privately; no automatic analysis. Only text and Markdown files can be analyzed currently.</p></div>
      <div style={{borderTop:'1px solid #e5dfd8',paddingTop:18,display:'grid',gap:14}}><label className="checkbox-row"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)} data-testid="checkbox-source-permission"/><span>I confirm I have permission to use and store this material in my workspace. <strong>Required.</strong></span></label><label className="checkbox-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} data-testid="checkbox-source-consent"/><span>I consent to making this source eligible for profile analysis. Analysis will still require another explicit confirmation.</span></label></div>
      {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
      <div className="dialog-actions"><button type="button" className="btn btn-outline" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy||!permission||!title.trim()||(!content.trim()&&!file)} data-testid="button-save-source">{busy?'Saving…':'Add source'}</button></div>
    </form></Modal>}
    {uploadedPath&&<div style={{marginTop:20}}><button className="btn btn-quiet" onClick={()=>objectQuery.refetch()} data-testid="button-verify-upload"><LockKeyhole/> Verify most recent private upload</button>{objectQuery.isSuccess&&<span className="badge green">Private object accessible</span>}{objectQuery.isError&&<span className="badge red">Unable to verify object</span>}</div>}
  </>;
}