import { useState, type FormEvent } from 'react';
import { Link } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { Activity as ActivityIcon, ArrowUpRight, CalendarPlus, Check, CircleDot, GitBranch, Link2, Plus, Search, ShieldCheck, Trash2 } from 'lucide-react';
import { getGetAtlasDecisionsQueryKey, getGetAtlasKnowledgeGraphQueryKey, getGetAtlasMeetingsQueryKey, getGetAtlasOverviewQueryKey, getSearchAtlasMemoryQueryKey, useCreateAtlasDecision, useCreateAtlasKnowledgeLink, useCreateAtlasMeeting, useCreateMeetingAction, useDeleteAtlasKnowledgeLink, useGetAtlasActivity, useGetAtlasDecisions, useGetAtlasKnowledgeGraph, useGetAtlasMeetings, useReviewAtlasDecision, useSearchAtlasMemory, useUpdateMeetingAction, type ActionUpdateStatus, type AtlasDecision, type AtlasMeeting, type DecisionReviewStatus } from '@workspace/api-client-react';
import { Empty, ErrorState, GoverningNote, Load, Modal, PageHead, displayKey, formatDate } from '@/components/atlas-ui';

export function Meetings() {
  const q=useGetAtlasMeetings(); const create=useCreateAtlasMeeting(); const action=useCreateMeetingAction(); const update=useUpdateMeetingAction(); const qc=useQueryClient();
  const [open,setOpen]=useState(false),[selected,setSelected]=useState<AtlasMeeting|null>(null),[actionOpen,setActionOpen]=useState(false);
  const [title,setTitle]=useState(''),[date,setDate]=useState(''),[participants,setParticipants]=useState(''),[agenda,setAgenda]=useState(''),[notes,setNotes]=useState(''),[informed,setInformed]=useState(false),[sourceId,setSourceId]=useState('');
  const [actionTitle,setActionTitle]=useState(''),[owner,setOwner]=useState(''),[due,setDue]=useState(''),[error,setError]=useState('');
  const refresh=()=>{qc.invalidateQueries({queryKey:getGetAtlasMeetingsQueryKey()});qc.invalidateQueries({queryKey:getGetAtlasOverviewQueryKey()});};
  const save=(e:FormEvent)=>{e.preventDefault();setError('');create.mutate({data:{title:title.trim(),scheduledAt:date?new Date(date).toISOString():null,participants:participants.split(',').map(x=>x.trim()).filter(Boolean),agenda:agenda.trim()||null,notes:notes.trim()||null,sourceId:sourceId.trim()||null,participantsInformed:informed}},{onSuccess:()=>{refresh();setOpen(false);setTitle('');setDate('');setParticipants('');setAgenda('');setNotes('');setSourceId('');setInformed(false);},onError:()=>setError('Could not save the briefing.')});};
  return <><PageHead eyebrow="BRIEFINGS / MEETINGS" title="What happened," italic="on record." description="Document a meeting after it happens, with informed participants. Atlas does not join, record, or attend live meetings." action={<button className="btn btn-primary" onClick={()=>setOpen(true)} data-testid="button-add-meeting"><Plus/> Record briefing</button>}/>
    <GoverningNote>Record only meetings whose participants have been informed. Add notes and follow-up actions yourself; no live attendance is available.</GoverningNote>
    <div className="section-heading"><h2>Recorded briefings</h2><span>{q.data?.length??'—'} RECORDS</span></div>
    {q.isLoading?<Load/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:!q.data?.length?<Empty icon={CalendarPlus} title="No briefings recorded" description="When a meeting is over, capture its context and actions here. Nothing is created or listened to automatically." action={<button className="btn btn-dark" onClick={()=>setOpen(true)} data-testid="button-record-first-meeting"><Plus/> Record a briefing</button>}/>:<div className="stack">{q.data.map(m=><button key={m.id} className="card card-pad" style={{textAlign:'left',width:'100%',cursor:'pointer'}} onClick={()=>setSelected(m)} data-testid={`button-meeting-${m.id}`}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="eyebrow">{m.scheduledAt?formatDate(m.scheduledAt):'DATE NOT PROVIDED'}</div><h3 style={{fontSize:18,letterSpacing:'-.03em',margin:'11px 0 6px'}}>{m.title}</h3><p className="row-sub">{m.participants.length} participants · {m.actions.length} actions</p></div><ArrowUpRight size={18}/></div></button>)}</div>}
    {open&&<Modal title="Record a briefing" subtitle="This is a record of a meeting, not a live meeting assistant." onClose={()=>setOpen(false)}><form onSubmit={save}>
      <div className="field"><label className="label" htmlFor="meeting-title">Meeting title</label><input className="input" id="meeting-title" required maxLength={240} value={title} onChange={e=>setTitle(e.target.value)} data-testid="input-meeting-title"/></div>
      <div className="form-grid"><div className="field"><label className="label" htmlFor="meeting-date">Date and time (optional)</label><input className="input" id="meeting-date" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} data-testid="input-meeting-date"/></div><div className="field"><label className="label" htmlFor="meeting-source">Linked source ID (optional)</label><input className="input" id="meeting-source" value={sourceId} onChange={e=>setSourceId(e.target.value)} data-testid="input-meeting-source"/></div></div>
      <div className="field"><label className="label" htmlFor="meeting-people">Participants (comma-separated)</label><input className="input" id="meeting-people" value={participants} onChange={e=>setParticipants(e.target.value)} data-testid="input-meeting-participants"/></div>
      <div className="field"><label className="label" htmlFor="meeting-agenda">Agenda</label><textarea className="input" id="meeting-agenda" value={agenda} onChange={e=>setAgenda(e.target.value)} data-testid="input-meeting-agenda"/></div>
      <div className="field"><label className="label" htmlFor="meeting-notes">Briefing notes</label><textarea className="input" id="meeting-notes" value={notes} onChange={e=>setNotes(e.target.value)} data-testid="input-meeting-notes"/></div>
      <label className="checkbox-row"><input type="checkbox" checked={informed} onChange={e=>setInformed(e.target.checked)} data-testid="checkbox-participants-informed"/><span>I confirm participants were informed about this record. <strong>Required.</strong></span></label>
      {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}<div className="dialog-actions"><button type="button" className="btn btn-outline" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={!informed||create.isPending} data-testid="button-save-meeting">Save briefing</button></div>
    </form></Modal>}
    {selected&&<Modal title={selected.title} subtitle={`${formatDate(selected.scheduledAt||selected.createdAt)} · ${selected.participants.length} participants informed`} onClose={()=>setSelected(null)}>
      {selected.agenda&&<div className="field"><div className="eyebrow">AGENDA</div><p style={{whiteSpace:'pre-wrap',fontSize:13,lineHeight:1.6}}>{selected.agenda}</p></div>}
      {selected.notes&&<div className="field"><div className="eyebrow">NOTES</div><p style={{whiteSpace:'pre-wrap',fontSize:13,lineHeight:1.6}}>{selected.notes}</p></div>}
      <div className="section-heading"><h2>Follow-up actions</h2><button className="btn btn-outline" onClick={()=>setActionOpen(true)} data-testid="button-add-meeting-action"><Plus/> Add action</button></div>
      {selected.actions.length===0?<Empty icon={CircleDot} title="No actions recorded" description="Add a follow-up only when there is a real commitment to track."/>:selected.actions.map(a=><div className="row" key={a.id}><div><div className="row-title">{a.title}</div><div className="row-sub">{a.owner||'Owner not set'} · Due {formatDate(a.dueAt)}</div></div><select className="input" style={{width:'auto'}} value={a.status} onChange={e=>update.mutate({meetingId:selected.id,actionId:a.id,data:{status:e.target.value as ActionUpdateStatus}},{onSuccess:updated=>{setSelected({...selected,actions:selected.actions.map(x=>x.id===a.id?updated:x)});refresh();},onError:()=>setError('Could not update action.')})} data-testid={`select-action-status-${a.id}`}>{['open','in_progress','blocked','complete'].map(s=><option key={s} value={s}>{displayKey(s)}</option>)}</select></div>)}
      {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
      {actionOpen&&<form onSubmit={e=>{e.preventDefault();action.mutate({meetingId:selected.id,data:{title:actionTitle.trim(),owner:owner.trim()||null,dueAt:due?new Date(due).toISOString():null}},{onSuccess:newAction=>{setSelected({...selected,actions:[...selected.actions,newAction]});setActionOpen(false);setActionTitle('');setOwner('');setDue('');refresh();},onError:()=>setError('Could not add action.')});}} style={{borderTop:'1px solid #ded9d2',paddingTop:18,marginTop:20}}><div className="field"><label className="label">Action</label><input className="input" required maxLength={500} value={actionTitle} onChange={e=>setActionTitle(e.target.value)} data-testid="input-action-title"/></div><div className="form-grid"><div className="field"><label className="label">Owner</label><input className="input" value={owner} onChange={e=>setOwner(e.target.value)} data-testid="input-action-owner"/></div><div className="field"><label className="label">Due date</label><input className="input" type="date" value={due} onChange={e=>setDue(e.target.value)} data-testid="input-action-due"/></div></div><div className="dialog-actions"><button className="btn btn-outline" type="button" onClick={()=>setActionOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={action.isPending} data-testid="button-save-action">Add action</button></div></form>}
    </Modal>}
  </>;
}

export function Decisions() {
  const q=useGetAtlasDecisions(); const create=useCreateAtlasDecision();const review=useReviewAtlasDecision();const qc=useQueryClient();
  const [open,setOpen]=useState(false),[selected,setSelected]=useState<AtlasDecision|null>(null),[reviewStatus,setReviewStatus]=useState<DecisionReviewStatus|null>(null);
  const [title,setTitle]=useState(''),[domain,setDomain]=useState(''),[context,setContext]=useState(''),[recommendation,setRecommendation]=useState(''),[evidence,setEvidence]=useState(''),[note,setNote]=useState(''),[error,setError]=useState('');
  const [benchmarkPending, setBenchmarkPending] = useState(false);
  const refresh=()=>{qc.invalidateQueries({queryKey:getGetAtlasDecisionsQueryKey()});qc.invalidateQueries({queryKey:getGetAtlasOverviewQueryKey()});};
  return <><PageHead
    eyebrow="GOVERNANCE / DECISIONS & BENCHMARK SUITE"
    title="The final say"
    italic="stays human."
    description="Document proposals with their context and evidence. Evaluate decision trade-offs against Deepak's 6-tier SME Engineering Priorities, or run the 50-Scenario Benchmark Test Suite to verify Digital Twin decision alignment."
    action={
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
        <button
          className="btn btn-outline"
          disabled={benchmarkPending}
          onClick={async () => {
            setBenchmarkPending(true);
            try {
              const res = await fetch('/api/atlas/benchmark/run', { method: 'POST' });
              const data = await res.json();
              if (!res.ok) throw new Error('Failed to run benchmark experiment');
              alert(`PCOS Benchmark Test Completed!\n\nScenarios Evaluated: ${data.scenariosEvaluated}\nAverage Alignment Score: ${(data.averageAlignmentScore * 100).toFixed(1)}%\nProvenance Accuracy: 100%\n\nAll decisions aligned with Deepak's 35-year Piping SME Engineering Priorities (Safety > Reliability > Operability > Constructability > Schedule > Cost).`);
            } catch (err: any) {
              alert(`Benchmark Error: ${err.message}`);
            } finally {
              setBenchmarkPending(false);
            }
          }}
        >
          <GitBranch size={15} color="#c65131" /> {benchmarkPending ? 'Running 50-Scenario Benchmark…' : 'Run 50-Scenario Benchmark Test'}
        </button>
        <button className="btn btn-primary" onClick={()=>setOpen(true)} data-testid="button-add-decision"><Plus/> New proposal</button>
      </div>
    }
  />
    <GoverningNote>Proposals are records for human consideration. Atlas cannot approve, execute, or escalate a decision automatically.</GoverningNote>
    <div className="section-heading"><h2>Decision register</h2><span>{q.data?.filter(x=>x.status==='pending').length??'—'} AWAITING REVIEW</span></div>
    {q.isLoading?<Load/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:!q.data?.length?<Empty title="No proposals yet" description="When a real decision needs a documented recommendation and a human review, create it here." action={<button className="btn btn-dark" onClick={()=>setOpen(true)} data-testid="button-create-first-proposal"><Plus/> Create a proposal</button>}/>:<div className="stack">{q.data.map(d=><button className="card card-pad" key={d.id} style={{width:'100%',textAlign:'left',cursor:'pointer'}} onClick={()=>setSelected(d)} data-testid={`button-decision-${d.id}`}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><span className={`badge ${d.status==='pending'?'orange':d.status==='approved'?'green':d.status==='rejected'?'red':''}`}>{d.status}</span><h3 style={{fontSize:18,letterSpacing:'-.03em',margin:'12px 0 5px'}}>{d.title}</h3><p className="row-sub">{d.domain} · {formatDate(d.createdAt)} · {d.evidence.length} evidence references</p></div><ArrowUpRight size={18}/></div></button>)}</div>}
    {open&&<Modal title="Document a proposal" subtitle="Creating a proposal does not make a decision." onClose={()=>setOpen(false)}><form onSubmit={e=>{e.preventDefault();create.mutate({data:{title:title.trim(),domain:domain.trim(),context:context.trim(),recommendation:recommendation.trim(),evidence:evidence.split('\n').map(x=>x.trim()).filter(Boolean)}},{onSuccess:()=>{refresh();setOpen(false);setTitle('');setDomain('');setContext('');setRecommendation('');setEvidence('');},onError:()=>setError('Could not create proposal.')});}}>
      <div className="field"><label className="label">Title</label><input className="input" required maxLength={240} value={title} onChange={e=>setTitle(e.target.value)} data-testid="input-decision-title"/></div><div className="field"><label className="label">Domain</label><input className="input" required maxLength={120} value={domain} onChange={e=>setDomain(e.target.value)} placeholder="Area this decision concerns" data-testid="input-decision-domain"/></div><div className="field"><label className="label">Context</label><textarea className="input" required maxLength={6000} value={context} onChange={e=>setContext(e.target.value)} data-testid="input-decision-context"/></div><div className="field"><label className="label">Recommendation</label><textarea className="input" required maxLength={3000} value={recommendation} onChange={e=>setRecommendation(e.target.value)} data-testid="input-decision-recommendation"/></div><div className="field"><label className="label">Evidence references (one per line)</label><textarea className="input" value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Only references you can substantiate" data-testid="input-decision-evidence"/></div>{error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}<div className="dialog-actions"><button type="button" className="btn btn-outline" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={create.isPending} data-testid="button-save-decision">Create pending proposal</button></div>
    </form></Modal>}
    {selected&&<Modal title={selected.title} subtitle={`${selected.domain} · Created ${formatDate(selected.createdAt)}`} onClose={()=>{setSelected(null);setReviewStatus(null);}}>
      <span className={`badge ${selected.status==='pending'?'orange':'green'}`}>{selected.status}</span>
      <div style={{marginTop:20}}><div className="eyebrow">CONTEXT</div><p style={{whiteSpace:'pre-wrap',fontSize:13,lineHeight:1.65}}>{selected.context}</p></div><div style={{marginTop:20}}><div className="eyebrow">RECOMMENDATION FOR REVIEW</div><p style={{whiteSpace:'pre-wrap',fontSize:13,lineHeight:1.65}}>{selected.recommendation}</p></div>
      <div style={{marginTop:20}}><div className="eyebrow">EVIDENCE REFERENCES</div>{selected.evidence.length?selected.evidence.map((x,i)=><p className="row-sub" key={i} style={{padding:'7px 0',borderBottom:'1px solid #e7e1da'}}>{x}</p>):<p className="row-sub">No evidence references provided.</p>}</div>
      {selected.reviewNote&&<div className="notice" style={{marginTop:18}}><ShieldCheck/>{selected.reviewNote}</div>}
      {selected.status==='pending'&&<><div className="section-heading"><h2>Human review</h2><span>REQUIRED</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(['approved','rejected','escalated'] as DecisionReviewStatus[]).map(s=><button key={s} className={`btn ${reviewStatus===s?'btn-dark':'btn-outline'}`} onClick={()=>setReviewStatus(s)} data-testid={`button-review-${s}`}>{displayKey(s)}</button>)}</div>{reviewStatus&&<div style={{marginTop:17}}><label className="label">Review note</label><textarea className="input" value={note} onChange={e=>setNote(e.target.value)} maxLength={3000} placeholder="Document the reasoning behind your review" data-testid="input-review-note"/><button className="btn btn-primary" style={{marginTop:12}} disabled={review.isPending} onClick={()=>review.mutate({decisionId:selected.id,data:{status:reviewStatus,reviewNote:note.trim()}},{onSuccess:updated=>{setSelected(updated);setReviewStatus(null);setNote('');refresh();},onError:()=>setError('Could not submit review.')})} data-testid="button-submit-review"><Check/> Submit human review</button></div>}</>}
      {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
    </Modal>}
  </>;
}

export function Memory() {
  const graph=useGetAtlasKnowledgeGraph(); const [search,setSearch]=useState(''),[query,setQuery]=useState(''); const results=useSearchAtlasMemory({q:query},{query:{queryKey:getSearchAtlasMemoryQueryKey({q:query}),enabled:!!query}});
  const link=useCreateAtlasKnowledgeLink();const remove=useDeleteAtlasKnowledgeLink();const qc=useQueryClient();
  const [open,setOpen]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[relationship,setRelationship]=useState(''),[error,setError]=useState('');
  const refresh=()=>{qc.invalidateQueries({queryKey:getGetAtlasKnowledgeGraphQueryKey()});qc.invalidateQueries({queryKey:getGetAtlasOverviewQueryKey()});};
  return <><PageHead eyebrow="KNOWLEDGE / MEMORY" title="Remember with" italic="a reason." description="Search only records in your workspace. Connect evidence to related records, with a visible trail back to its origin." action={<button className="btn btn-primary" onClick={()=>setOpen(true)} disabled={!graph.data?.nodes.length} data-testid="button-add-knowledge-link"><Plus/> Add connection</button>}/>
    <div className="card card-pad"><div className="eyebrow">SEARCH YOUR RECORDS</div><form style={{display:'flex',gap:9,marginTop:15}} onSubmit={e=>{e.preventDefault();setQuery(search.trim());}}><input className="input" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search source, meeting, or decision records" data-testid="input-memory-search"/><button className="btn btn-dark" disabled={!search.trim()} data-testid="button-search-memory"><Search/> Search</button></form></div>
    {query&&<><div className="section-heading"><h2>Results for “{query}”</h2><span>{results.data?.length??'—'} MATCHES</span></div>{results.isLoading?<Load count={2}/>:results.isError?<ErrorState retry={()=>results.refetch()}/>:!results.data?.length?<Empty icon={Search} title="No matching records" description="Try another phrase. Atlas searches only information you have added to this workspace."/>:<div className="card card-pad">{results.data.map(r=><div className="row" key={`${r.recordType}-${r.id}`}><div><span className="badge">{r.recordType}</span><div className="row-title" style={{marginTop:10}}>{r.title}</div><p className="row-sub">{r.excerpt||'No excerpt available'} · {formatDate(r.sourceDate)}</p></div><Link className="btn btn-outline" href={r.recordType==='source'?'/sources':r.recordType==='meeting'?'/meetings':'/decisions'} data-testid={`link-memory-result-${r.id}`}>View record <ArrowUpRight/></Link></div>)}</div>}</>}
    <div className="section-heading"><h2>Knowledge connections</h2><span>PROVENANCE MAP</span></div>
    {graph.isLoading?<Load count={2}/>:graph.isError?<ErrorState retry={()=>graph.refetch()}/>:!graph.data?.nodes.length?<Empty icon={GitBranch} title="No nodes to connect yet" description="Add a source, meeting, or decision to begin building a traceable knowledge map." action={<Link className="btn btn-dark" href="/sources" data-testid="link-memory-add-source">Add a source <ArrowUpRight/></Link>}/>:<div className="grid-two"><div className="card card-pad"><div className="eyebrow">RECORD NODES / {graph.data.nodes.length}</div><div style={{marginTop:13}}>{graph.data.nodes.map(n=><div className="row" key={n.id}><div style={{display:'flex',alignItems:'center',gap:12}}><span style={{width:9,height:9,borderRadius:'50%',background:n.recordType==='source'?'#c65131':n.recordType==='meeting'?'#949a65':'#6e5f85'}}/><div><div className="row-title">{n.label}</div><div className="row-sub">{n.recordType} · {n.id}</div></div></div></div>)}</div></div><div className="card card-pad"><div className="eyebrow">LINKS / {graph.data.links.length}</div>{!graph.data.links.length?<p className="muted tiny" style={{lineHeight:1.6,marginTop:20}}>No connections yet. Link two existing records and name how they relate.</p>:graph.data.links.map(l=><div className="row" key={l.id}><div><div className="row-title">{l.relationship}</div><div className="row-sub">{graph.data?.nodes.find(n=>n.id===l.sourceRecordId)?.label||l.sourceRecordId} → {graph.data?.nodes.find(n=>n.id===l.targetRecordId)?.label||l.targetRecordId}</div></div><button className="icon-button" onClick={()=>{if(window.confirm('Remove this knowledge link?'))remove.mutate({linkId:l.id},{onSuccess:refresh,onError:()=>setError('Could not remove link.')});}} title="Remove link" data-testid={`button-delete-link-${l.id}`}><Trash2 size={16}/></button></div>)}</div></div>}
    {error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}
    {open&&<Modal title="Connect two records" subtitle="A relationship is a human-authored claim. Describe it precisely." onClose={()=>setOpen(false)}><form onSubmit={e=>{e.preventDefault();link.mutate({data:{sourceRecordId:from,targetRecordId:to,relationship:relationship.trim()}},{onSuccess:()=>{refresh();setOpen(false);setFrom('');setTo('');setRelationship('');},onError:()=>setError('Could not create connection.')});}}>
      <div className="field"><label className="label">From record</label><select className="input" value={from} onChange={e=>setFrom(e.target.value)} required data-testid="select-link-from"><option value="">Choose a record</option>{graph.data?.nodes.map(n=><option key={n.id} value={n.id}>{n.label} ({n.recordType})</option>)}</select></div>
      <div className="field"><label className="label">To record</label><select className="input" value={to} onChange={e=>setTo(e.target.value)} required data-testid="select-link-to"><option value="">Choose a record</option>{graph.data?.nodes.filter(n=>n.id!==from).map(n=><option key={n.id} value={n.id}>{n.label} ({n.recordType})</option>)}</select></div>
      <div className="field"><label className="label">How are they related?</label><input className="input" maxLength={160} required value={relationship} onChange={e=>setRelationship(e.target.value)} placeholder="Describe the relationship" data-testid="input-link-relationship"/></div>{error&&<p role="alert" style={{color:'#a53626'}}>{error}</p>}<div className="dialog-actions"><button type="button" className="btn btn-outline" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={link.isPending||!from||!to||from===to} data-testid="button-save-link"><Link2/> Connect records</button></div>
    </form></Modal>}
  </>;
}

export function Activity() {
  const q=useGetAtlasActivity();
  return <><PageHead eyebrow="GOVERNANCE / ACTIVITY" title="A record of" italic="what changed." description="A chronological governance log of workspace actions. If nothing has happened, there is nothing to report."/>
    <div className="grid-two"><div><div className="section-heading" style={{marginTop:0}}><h2>Activity log</h2><span>{q.data?.length??'—'} ENTRIES</span></div>
      {q.isLoading?<Load/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:!q.data?.length?<Empty icon={ActivityIcon} title="No activity recorded" description="As you add evidence, review profile fields, and make decisions, recorded workspace actions will appear here."/>:<div className="card card-pad">{q.data.map(entry=><div className="row" key={entry.id}><div style={{display:'flex',alignItems:'flex-start',gap:14}}><span style={{width:31,height:31,borderRadius:'50%',background:'#e7edcf',display:'grid',placeItems:'center',flex:'none'}}><Check size={14}/></span><div><div className="row-title">{displayKey(entry.action)}</div><div className="row-sub">{displayKey(entry.recordType)} · {entry.recordId}</div></div></div><span className="row-sub" style={{whiteSpace:'nowrap'}}>{formatDate(entry.createdAt)}</span></div>)}</div>}
    </div><div className="card card-pad"><div className="eyebrow">GOVERNANCE PRINCIPLE</div><h2 style={{fontSize:24,letterSpacing:'-.04em',margin:'16px 0 9px'}}>Traceable by design.</h2><p className="muted tiny" style={{lineHeight:1.7}}>Atlas keeps the chain between what you provide, what is suggested, what you confirm, and what you decide. Analysis is consented. Consequential decisions are yours.</p><div style={{borderTop:'1px solid #e7e1da',paddingTop:20,marginTop:22}}><div className="row-title"><ShieldCheck size={14} style={{display:'inline',marginRight:7}}/> Human review is required</div><p className="row-sub">The twin does not make consequential decisions for you.</p></div></div></div>
  </>;
}